### ISSUE TITLE
implement python type hinting

### ISSUE THREAD

**Issue by rlskoeser** [dh-tech/hackathon-2022#11]
seems like type hinting would be pretty valuable in this package (esp. since we should support comparing to standard `datetime` objects when we can, but should be explicit about it)

https://docs.python.org/3.9/library/typing.html
https://peps.python.org/pep-0483/

**Comment by ColeDCrawford** [comment]
Definitely agree on this. `3.10` has better support than `3.9` for generic types. Probably a different question, but is there a Python version we should keep in mind when developing?

I've used type hints in a couple projects, but haven't used something like `mypy` to enforce them. Probably a two-step process but that would be a good goal.

**Comment by ColeDCrawford** [comment]
I think type hinting was added in `3.5`, f-strings in `3.6`. Typing is part of the standard lib so I think to get newer typing features you have to use a newer version of Python. You can backport typing to pre-3.5 with a library install.

I have one project on `3.5`, several on `3.8`, and one each on `3.9` and `3.10`.

**Comment by rlskoeser** [comment]
I have a couple of projects still on 3.6 (hopefully will be able to update before too long, but you know how that goes...). 3.5 and 3.6 are already EOL ? Based on this [python versions timeline](https://devguide.python.org/versions/) it seems like we shouldn't be targeting 3.6 and maybe not bother with 3.7 either (unless community needs it).

What's the oldest project / version of pyhton you've got where you'd be interested in using `undate` ?

**Comment by ColeDCrawford** [comment]
Probably `3.8`, but I should update those to `3.10` soon anyway.

**Comment by rlskoeser** [comment]
3.8 seems like a good minimum target to me! unless it's causes substantial extra effort for working with the code

**Comment by rlskoeser** [comment]
completed in #16 — thanks @ColeDCrawford ! 🎉
