### ISSUE TITLE
Convert setup.py to new recommended format of setup.cfg + pyproject.toml

### ISSUE THREAD

**Issue by rlskoeser** [dh-tech/hackathon-2022#28]
> Any reason to use `setup.py` vs `setup.cfg` + `pyproject.toml`? Think I've usually followed a structure somewhat like this for packages I think will be distributed: https://setuptools.pypa.io/en/latest/userguide/declarative_config.html.

_Originally posted by @ColeDCrawford in https://github.com/dh-tech/hackathon-2022/pull/27#discussion_r1019276580_

**Comment by maltevogl** [comment]
I try to to a quick fix for transforming to setup.cfg and address #37 as well.

**Comment by rlskoeser** [comment]
completed in #49
